class Pin:
    def __init__(self, id, name):
        self.id = id
        self.name = name

OLED_BUTTON_NEXT = Pin(15, "OLED_BUTTON_NEXT")
OLED_BUTTON_SELECT = Pin(17, "OLED_BUTTON_SELECT")
BUTTON_WASHING = Pin(0, "BUTTON_WASHING")
BUTTON_COOLING = Pin(1, "BUTTON_COOLING")
BUTTON_MIXING = Pin(16, "BUTTON_MIXING")

VENTIL_HLADNA = Pin(18, "VENTIL_HLADNA")
VENTIL_TOPLA = Pin(19, "VENTIL_TOPLA")
MOTOR = Pin(20, "MOTOR")
VENTIL_ISPUST = Pin(21, "VENTIL_ISPUST")
DOZIRANJE_LUZINA = Pin(26, "DOZIRANJE_LUZINA")
DOZIRANJE_KISELINA = Pin(27, "DOZIRANJE_KISELINA")
KOMPRESOR = Pin(28, "KOMPRESOR")
MIXER = Pin(22, "MIXER")

OLED_SPI_MOSI = Pin(11, "OLED_SPI_MOSI")
OLED_SPI_SCK = Pin(10, "OLED_SPI_SCK")
OLED_RST = Pin(12, "OLED_RST")
OLED_SPI_DC = Pin(8, "OLED_SPI_DC")
OLED_SPI_CS = Pin(9, "OLED_SPI_CS")
ONBOARD_LED = Pin("LED", "ONBOARD_LED")

MAX_SPI_CS = Pin(5, "MAX_SPI_CS")
MAX_SPI_MOSI =  Pin(3, "MAX_SPI_MOSI")
MAX_SPI_MISO =  Pin(4, "MAX_SPI_MISO")
MAX_SPI_SCK =  Pin(2, "MAX_SPI_SCK")
